Add csuite to aosp-build-tools manifest
The art project now contains a csuite_test module, which causes a
blueprint failure:
error: art/test/Android.bp:1317:1: unrecognized module type "csuite_test"

Add the csuite project that defines the module type.  This will
also add csuite_test to go/Android.bp.

Test: aosp-build-tools build
Change-Id: I6eaa806b50b76d9e88bb440b4a3be9278eab6614