Remove vendor/arm/mali projects to fix broken builds
A few of the targets are broken by the following errors:
error: vendor/arm/mali/valhall/tpi/egl/android_vndk/Android.bp:59:1: module "extract_libgui64": depends on disabled module "libdepend_on_libgui64"

and

error: vendor/arm/mali/valhall/Android.bp:44217:1: module "link_with_libgui_vendor_stub" variant "android_vendor.S_x86_64_static": module "libgui.vendor.stub" is not a shared library

Removing them until they can be resolved to get builds green again

Bug: 172746156
Signed-off-by: Patrick Tjin <pattjin@google.com>
Change-Id: I65718fcc1cd8112f59a2a8894187b92f934ab862