Add external/tensorflow to pdk needed by libnnbenchmark
error: frameworks/ml/nn/runtime/test/benchmark/libnnbenchmark/Android.bp:15:1:
"libnnbenchmark" depends on undefined module "libtflite_static"

Fixes: 70732901