superproject - add contactinfo and bugurl to file bugs in manifest.
Bug: 186220520
Tested: manual

$ repo_dev sync
WARNING: --use-superproject is experimental and not for general use
/usr/local/google/home/rtenneti/work/drive2/android/internal-master/.repo/exp-superproject/feb2c2847da5e274f3d530d5ab438af8-superproject.git: Initial setup for superproject completed.
error: please file a bug using go/repo-bug to report missing commit_ids for: []
error: Update of revsionId from superproject has failed. Please resync with --no-use-superproject option

Change-Id: I3e0e7e5266e9c994fae94fa40111b63494d181fe
Merged-In: I3e0e7e5266e9c994fae94fa40111b63494d181fe
(cherry picked from commit 5aa5e28fb604d39975fec209b4d09f54d52c0fd5)