Don't include "dalvik" and "libcore" on Windows
"dalvik" and "libcore" were added in a previous CL
(https://googleplex-android-review.git.corp.google.com/1665776/)
but that causes "repo sync" to fail on Windows.

The reason is that git fails to sync "libcore" on Windows because
a file (luni/src/test/resources/org/apache/harmony/tests/java/lang/
test?.properties) contains a "? character in its name, which is not
legal on Windows.

The error message during repo sync:

error: unable to create file luni/src/test/resources/org/apache/harmony/tests/java/lang/test?.properties: Invalid argument

Test: Manually verified that "repo sync" works again, Windows builbot
will also hopefully be fixed.

Change-Id: Ib527638ca79aef934cb407983b2f62f2b7ec671e
Reviewed-on: https://googleplex-android-review.git.corp.google.com/1670047
Reviewed-by: Renaud Paquay <rpaquay@google.com>
Reviewed-by: Xavier Ducrohet <xav@google.com>
Presubmit-Verified: TreeHugger Robot <treehugger-gerrit@google.com>